const crypto = require('crypto');

const TABLE = 'cashflow_leads';
function clean(v, n = 500) { return String(v || '').replace(/[\u0000-\u001f\u007f]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, n); }
function esc(v) { return clean(v, 2000).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function json(res, status, body) { res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.setHeader('Cache-Control', 'no-store'); res.end(JSON.stringify(body)); }
function botToken() { const v = clean(process.env.TELEGRAM_BOT_TOKEN, 500); return /^\d+:[A-Za-z0-9_-]{20,}$/.test(v) ? v : ''; }
function secret() { return crypto.createHash('sha256').update(clean(process.env.LEAD_WEBHOOK_SECRET, 1000)).digest('hex'); }
function db() { const url = clean(process.env.SUPABASE_URL, 600).replace(/\/+$/, ''); const key = clean(process.env.SUPABASE_SERVICE_ROLE_KEY, 6000); return url && key ? { url, key } : null; }
function dbHeaders(c) { const h = { apikey: c.key, 'Content-Type': 'application/json', Prefer: 'return=representation' }; if (!c.key.startsWith('sb_secret_')) h.Authorization = `Bearer ${c.key}`; return h; }
async function telegram(method, payload) { const r = await fetch(`https://api.telegram.org/bot${botToken()}/${method}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const d = await r.json(); if (!r.ok || !d.ok) throw new Error(`telegram_${method}_${r.status}`); return d.result; }
async function supabase(path, method = 'GET', body) { const c = db(); if (!c) throw new Error('db_missing'); const r = await fetch(`${c.url}/rest/v1/${path}`, { method, headers: dbHeaders(c), body: body === undefined ? undefined : JSON.stringify(body) }); const t = await r.text(); let d = null; try { d = t ? JSON.parse(t) : null; } catch (_) {} if (!r.ok) throw new Error(`db_${r.status}`); return d; }
function buttons(lead) { const id = clean(lead.id, 100); return { inline_keyboard: [[{ text: '✅ Kontaktiert', callback_data: `st:contacted:${id}` }, { text: '⭐ Qualifiziert', callback_data: `st:qualified:${id}` }], [{ text: '📅 Termin', callback_data: `st:calendar_opened:${id}` }, { text: '🏆 Gewonnen', callback_data: `out:won:${id}` }], [{ text: '❌ Verloren', callback_data: `out:lost:${id}` }]] }; }
function leadText(l, title = 'LEAD') { const q = l.qualification || {}; const notes = Array.isArray(q.notes) ? q.notes : []; return [`<b>${title}</b>`, '', `👤 <b>${esc(l.first_name)}</b>`, `📞 <code>${esc(l.phone)}</code>`, `✉️ ${esc(l.email)}`, `📌 Status: <b>${esc(l.status)}</b>`, notes.length ? `📝 ${esc(notes[notes.length - 1].text)}` : '', `🆔 <code>${esc(l.id)}</code>`].filter(Boolean).join('\n'); }
async function showLead(chatId, lead, title) { await telegram('sendMessage', { chat_id: chatId, text: leadText(lead, title), parse_mode: 'HTML', reply_markup: buttons(lead) }); }
async function recent(limit = 8, today = false) { let p = `${TABLE}?select=*&order=created_at.desc&limit=${limit}`; if (today) { const d = new Date(); d.setUTCHours(0,0,0,0); p += `&created_at=gte.${encodeURIComponent(d.toISOString())}`; } return await supabase(p) || []; }
async function patch(id, data) { const rows = await supabase(`${TABLE}?id=eq.${encodeURIComponent(id)}&select=*`, 'PATCH', { ...data, updated_at: new Date().toISOString() }); return rows && rows[0]; }
async function searchLead(term) { const e = encodeURIComponent(`*${clean(term,180)}*`); return await supabase(`${TABLE}?select=*&or=(id.ilike.${e},first_name.ilike.${e},email.ilike.${e},phone.ilike.${e})&order=created_at.desc&limit=5`) || []; }
function help() { return '<b>Julian Lead Bot</b>\n\n/neu – offene Leads\n/heute – heutige Leads\n/lead Name – suchen\n/notiz ID Text – Notiz speichern\n/zahlen – Tagesübersicht\n/status – Systemstatus\n/help – Hilfe'; }
async function command(chatId, text) {
  const parts = clean(text, 1200).split(' '); const cmd = parts.shift().toLowerCase().split('@')[0];
  if (cmd === '/start' || cmd === '/help') return telegram('sendMessage', { chat_id: chatId, text: help(), parse_mode: 'HTML' });
  if (cmd === '/neu' || cmd === '/heute') { let leads = await recent(cmd === '/heute' ? 10 : 12, cmd === '/heute'); if (cmd === '/neu') leads = leads.filter(l => ['new','callback_requested','calendar_opened'].includes(l.status)).slice(0,5); if (!leads.length) return telegram('sendMessage', { chat_id: chatId, text: 'Keine passenden Leads gefunden.' }); for (const l of leads.slice(0,8)) await showLead(chatId, l, cmd === '/heute' ? 'HEUTIGER LEAD' : 'OFFENER LEAD'); return; }
  if (cmd === '/lead') { const leads = await searchLead(parts.join(' ')); if (!leads.length) return telegram('sendMessage', { chat_id: chatId, text: 'Kein Lead gefunden.' }); for (const l of leads) await showLead(chatId, l, 'GEFUNDENER LEAD'); return; }
  if (cmd === '/notiz') { const id = parts.shift(); const note = parts.join(' '); if (!id || !note) return telegram('sendMessage', { chat_id: chatId, text: 'Format: /notiz LEAD-ID Deine Notiz' }); const rows = await supabase(`${TABLE}?id=eq.${encodeURIComponent(id)}&select=id,qualification&limit=1`); if (!rows || !rows[0]) return telegram('sendMessage', { chat_id: chatId, text: 'Lead nicht gefunden.' }); const q = rows[0].qualification || {}; const notes = Array.isArray(q.notes) ? q.notes.slice(-19) : []; notes.push({ text: clean(note,600), at: new Date().toISOString(), by: 'Julian' }); await patch(id, { qualification: { ...q, notes } }); return telegram('sendMessage', { chat_id: chatId, text: '📝 Notiz gespeichert.' }); }
  if (cmd === '/zahlen') { const leads = await recent(100, true); const c = s => leads.filter(l => l.status === s).length; return telegram('sendMessage', { chat_id: chatId, parse_mode: 'HTML', text: `<b>HEUTE</b>\n\n🚨 Leads: <b>${leads.length}</b>\n🆕 Neu: <b>${c('new')}</b>\n📞 Kontaktiert: <b>${c('contacted')}</b>\n⭐ Qualifiziert: <b>${c('qualified')}</b>\n📅 Terminwahl: <b>${c('calendar_opened')}</b>\n✅ Abgeschlossen: <b>${c('closed')}</b>` }); }
  if (cmd === '/status') { let ok = true; try { await recent(1); } catch (_) { ok = false; } return telegram('sendMessage', { chat_id: chatId, parse_mode: 'HTML', text: `<b>SYSTEMSTATUS</b>\n\nTelegram: ✅\nSupabase: ${ok ? '✅' : '❌'}\nWebsite: ✅` }); }
  return telegram('sendMessage', { chat_id: chatId, text: 'Unbekannter Befehl. Nutze /help.' });
}
async function callback(q) { const chatId = String(q.message.chat.id); const [kind, value, id] = clean(q.data, 240).split(':'); let lead = null; if (kind === 'st' && ['contacted','qualified','calendar_opened'].includes(value)) lead = await patch(id, { status: value, ...(value === 'calendar_opened' ? { contact_preference: 'calendar' } : {}) }); if (kind === 'out' && ['won','lost'].includes(value)) { const rows = await supabase(`${TABLE}?id=eq.${encodeURIComponent(id)}&select=id,qualification&limit=1`); const qual = rows && rows[0] && rows[0].qualification || {}; lead = await patch(id, { status: 'closed', qualification: { ...qual, outcome: value, outcome_at: new Date().toISOString() } }); } await telegram('answerCallbackQuery', { callback_query_id: q.id, text: lead ? 'Gespeichert ✅' : 'Nicht gespeichert.' }); if (lead) await telegram('editMessageText', { chat_id: chatId, message_id: q.message.message_id, text: leadText(lead, 'LEAD AKTUALISIERT'), parse_mode: 'HTML', reply_markup: buttons(lead) }); }
module.exports = async function handler(req, res) { if (req.method !== 'POST') return json(res,405,{ok:false}); if (clean(req.headers['x-telegram-bot-api-secret-token'],200) !== secret()) return json(res,401,{ok:false}); let u = req.body; if (typeof u === 'string') { try { u = JSON.parse(u); } catch (_) { u = {}; } } try { const from = u.message && u.message.from || u.callback_query && u.callback_query.from || {}; const chatId = String(u.message && u.message.chat.id || u.callback_query && u.callback_query.message.chat.id || ''); const isJulian = clean(from.first_name,100).toLowerCase() === 'julian'; if (!isJulian) { if (chatId) await telegram('sendMessage',{chat_id:chatId,text:'Dieser Bot ist nur für Julian freigeschaltet.'}); return json(res,200,{ok:true,ignored:true}); } if (u.callback_query) await callback(u.callback_query); else if (u.message && u.message.text) await command(chatId,u.message.text); } catch (e) { console.error('Telegram bot command failed:',e.message); } return json(res,200,{ok:true}); };
